name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest  # This is the GitHub runner, not your EC2 OS

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy project files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Run post-deploy commands on EC2 (Linux/UNIX)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install Apache (for Debian/Ubuntu)
            if [ -f /etc/debian_version ]; then
              sudo apt-get update -y
              sudo apt-get install -y apache2
              sudo systemctl start apache2
              sudo systemctl enable apache2
            fi

            # For Amazon Linux (yum based)
            if [ -f /etc/system-release ]; then
              sudo yum update -y
              sudo yum install -y httpd
              sudo systemctl start httpd
              sudo systemctl enable httpd
            fi

            # Move project files to web directory
            if [ -d ~/ ]; then
              sudo cp -r ${{ secrets.TARGET_DIR }}/* /var/www/html/
              sudo chown -R apache:apache /var/www/html/  # or www-data:www-data depending on OS
              sudo systemctl restart apache2 || sudo systemctl restart httpd
            fi
